name: Build LaTeX document
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        run: |
          pandoc `ls -I "README.md" linux/` -o linux.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: linux.pdf