name: Build PDF document
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile PDF document
        run: |
          list=`ls -d linux/*[!README].md`
          pandoc $list -o linux.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: linux.pdf
